FROM node:20-bookworm-slim

#create a folder for global library

WORKDIR /base

# Pre-install the React heavy-lifters

# RUN npm install react react-dom vite @vitejs/plugin-react-swc
RUN npm install react react-dom vite @vitejs/plugin-react

# Set the path so Node can see these modules from anywhere

ENV NODE_PATH=/base/node_modules

# Go back to the app folder where the user's code will live
WORKDIR /app
    